<?php 
    $a1 = "SELECT price FROM farechart WHERE fromstn = 'Bangalore' AND tostn = 'Chennai' LIMIT 1";
    $a2 = "SELECT price FROM farechart WHERE fromstn = 'Bangalore' AND tostn = 'Hyderabad' LIMIT 1";
    $a3 = "SELECT price FROM farechart WHERE fromstn = 'Bangalore' AND tostn = 'Kolkata' LIMIT 1";
    $a4 = "SELECT price FROM farechart WHERE fromstn = 'Bangalore' AND tostn = 'Mumbai' LIMIT 1";
    $a5 = "SELECT price FROM farechart WHERE fromstn = 'Bangalore' AND tostn = 'New Delhi' LIMIT 1";
    $b1 = "SELECT price FROM farechart WHERE fromstn = 'Chennai' AND tostn = 'Bangalore' LIMIT 1";
    $b2 = "SELECT price FROM farechart WHERE fromstn = 'Chennai' AND tostn = 'Hyderabad' LIMIT 1";
    $b3 = "SELECT price FROM farechart WHERE fromstn = 'Chennai' AND tostn = 'Kolkata' LIMIT 1";
    $b4 = "SELECT price FROM farechart WHERE fromstn = 'Chennai' AND tostn = 'Mumbai' LIMIT 1";
    $b5 = "SELECT price FROM farechart WHERE fromstn = 'Chennai' AND tostn = 'New Delhi' LIMIT 1";
    $c1 = "SELECT price FROM farechart WHERE fromstn = 'Hyderabad' AND tostn = 'Bangalore' LIMIT 1";
    $c2 = "SELECT price FROM farechart WHERE fromstn = 'Hyderabad' AND tostn = 'Chennai' LIMIT 1";
    $c3 = "SELECT price FROM farechart WHERE fromstn = 'Hyderabad' AND tostn = 'Kolkata' LIMIT 1";
    $c4 = "SELECT price FROM farechart WHERE fromstn = 'Hyderabad' AND tostn = 'Mumbai' LIMIT 1";
    $c5 = "SELECT price FROM farechart WHERE fromstn = 'Hyderabad' AND tostn = 'New Delhi' LIMIT 1";
    $d1 = "SELECT price FROM farechart WHERE fromstn = 'Kolkata' AND tostn = 'Bangalore' LIMIT 1";
    $d2 = "SELECT price FROM farechart WHERE fromstn = 'Kolkata' AND tostn = 'Chennai' LIMIT 1";
    $d3 = "SELECT price FROM farechart WHERE fromstn = 'Kolkata' AND tostn = 'Hyderabad' LIMIT 1";
    $d4 = "SELECT price FROM farechart WHERE fromstn = 'Kolkata' AND tostn = 'Mumbai' LIMIT 1";
    $d5 = "SELECT price FROM farechart WHERE fromstn = 'Kolkata' AND tostn = 'New Delhi' LIMIT 1";
    $e1 = "SELECT price FROM farechart WHERE fromstn = 'Mumbai' AND tostn = 'Bangalore' LIMIT 1";
    $e2 = "SELECT price FROM farechart WHERE fromstn = 'Mumbai' AND tostn = 'Chennai' LIMIT 1";
    $e3 = "SELECT price FROM farechart WHERE fromstn = 'Mumbai' AND tostn = 'Hyderabad' LIMIT 1";
    $e4 = "SELECT price FROM farechart WHERE fromstn = 'Mumbai' AND tostn = 'Kolkata' LIMIT 1";
    $e5 = "SELECT price FROM farechart WHERE fromstn = 'Mumbai' AND tostn = 'New Delhi' LIMIT 1";
    $f1 = "SELECT price FROM farechart WHERE fromstn = 'New Delhi' AND tostn = 'Bangalore' LIMIT 1";
    $f2 = "SELECT price FROM farechart WHERE fromstn = 'New Delhi' AND tostn = 'Chennai' LIMIT 1";
    $f3 = "SELECT price FROM farechart WHERE fromstn = 'New Delhi' AND tostn = 'Hyderabad' LIMIT 1";
    $f4 = "SELECT price FROM farechart WHERE fromstn = 'New Delhi' AND tostn = 'Kolkata' LIMIT 1";
    $f5 = "SELECT price FROM farechart WHERE fromstn = 'New Delhi' AND tostn = 'Mumbai' LIMIT 1";
    $g1 = "SELECT price FROM class WHERE class = 'General' LIMIT 1";
    $g2 = "SELECT price FROM class WHERE class = 'Chair Car' LIMIT 1";
    $g3 = "SELECT price FROM class WHERE class = 'Sleeper' LIMIT 1";
    $g4 = "SELECT price FROM class WHERE class = 'AC Three Tier' LIMIT 1";
    $g5 = "SELECT price FROM class WHERE class = 'AC Two Tier' LIMIT 1";
    $g6 = "SELECT price FROM class WHERE class = 'AC First Class' LIMIT 1";
    $h1 = "SELECT price FROM trains WHERE traintype = 'Rajdhani' LIMIT 1";
    $h2 = "SELECT price FROM trains WHERE traintype = 'Jan Shatabdi' LIMIT 1";
    $h3 = "SELECT price FROM trains WHERE traintype = 'Express' LIMIT 1";
    $querya1 = mysqli_query($db, $a1);
    $querya2 = mysqli_query($db, $a2);
    $querya3 = mysqli_query($db, $a3);
    $querya4 = mysqli_query($db, $a4);
    $querya5 = mysqli_query($db, $a5);
    $queryb1 = mysqli_query($db, $b1);
    $queryb2 = mysqli_query($db, $b2);
    $queryb3 = mysqli_query($db, $b3);
    $queryb4 = mysqli_query($db, $b4);
    $queryb5 = mysqli_query($db, $b5);
    $queryc1 = mysqli_query($db, $c1);
    $queryc2 = mysqli_query($db, $c2);
    $queryc3 = mysqli_query($db, $c3);
    $queryc4 = mysqli_query($db, $c4);
    $queryc5 = mysqli_query($db, $c5);
    $queryd1 = mysqli_query($db, $d1);
    $queryd2 = mysqli_query($db, $d2);
    $queryd3 = mysqli_query($db, $d3);
    $queryd4 = mysqli_query($db, $d4);
    $queryd5 = mysqli_query($db, $d5);
    $querye1 = mysqli_query($db, $e1);
    $querye2 = mysqli_query($db, $e2);
    $querye3 = mysqli_query($db, $e3);
    $querye4 = mysqli_query($db, $e4);
    $querye5 = mysqli_query($db, $e5);
    $queryf1 = mysqli_query($db, $f1);
    $queryf2 = mysqli_query($db, $f2);
    $queryf3 = mysqli_query($db, $f3);
    $queryf4 = mysqli_query($db, $f4);
    $queryf5 = mysqli_query($db, $f5);
    $queryg1 = mysqli_query($db, $g1);
    $queryg2 = mysqli_query($db, $g2);
    $queryg3 = mysqli_query($db, $g3);
    $queryg4 = mysqli_query($db, $g4);
    $queryg5 = mysqli_query($db, $g5);
    $queryg6 = mysqli_query($db, $g6);
    $queryh1 = mysqli_query($db, $h1);
    $queryh2 = mysqli_query($db, $h2);
    $queryh3 = mysqli_query($db, $h3);
    $fetcha1 = mysqli_fetch_row($querya1);
    $fetcha2 = mysqli_fetch_row($querya2);
    $fetcha3 = mysqli_fetch_row($querya3);
    $fetcha4 = mysqli_fetch_row($querya4);
    $fetcha5 = mysqli_fetch_row($querya5);
    $fetchb1 = mysqli_fetch_row($queryb1);
    $fetchb2 = mysqli_fetch_row($queryb2);
    $fetchb3 = mysqli_fetch_row($queryb3);
    $fetchb4 = mysqli_fetch_row($queryb4);
    $fetchb5 = mysqli_fetch_row($queryb5);
    $fetchc1 = mysqli_fetch_row($queryc1);
    $fetchc2 = mysqli_fetch_row($queryc2);
    $fetchc3 = mysqli_fetch_row($queryc3);
    $fetchc4 = mysqli_fetch_row($queryc4);
    $fetchc5 = mysqli_fetch_row($queryc5);
    $fetchd1 = mysqli_fetch_row($queryd1);
    $fetchd2 = mysqli_fetch_row($queryd2);
    $fetchd3 = mysqli_fetch_row($queryd3);
    $fetchd4 = mysqli_fetch_row($queryd4);
    $fetchd5 = mysqli_fetch_row($queryd5);
    $fetche1 = mysqli_fetch_row($querye1);
    $fetche2 = mysqli_fetch_row($querye2);
    $fetche3 = mysqli_fetch_row($querye3);
    $fetche4 = mysqli_fetch_row($querye4);
    $fetche5 = mysqli_fetch_row($querye5);
    $fetchf1 = mysqli_fetch_row($queryf1);
    $fetchf2 = mysqli_fetch_row($queryf2);
    $fetchf3 = mysqli_fetch_row($queryf3);
    $fetchf4 = mysqli_fetch_row($queryf4);
    $fetchf5 = mysqli_fetch_row($queryf5);
    $fetchg1 = mysqli_fetch_row($queryg1);
    $fetchg2 = mysqli_fetch_row($queryg2);
    $fetchg3 = mysqli_fetch_row($queryg3);
    $fetchg4 = mysqli_fetch_row($queryg4);
    $fetchg5 = mysqli_fetch_row($queryg5);
    $fetchg6 = mysqli_fetch_row($queryg6);
    $fetchh1 = mysqli_fetch_row($queryh1);
    $fetchh2 = mysqli_fetch_row($queryh2);
    $fetchh3 = mysqli_fetch_row($queryh3);
?>